-- gl_je_batches 日记帐批表
create table GL_JE_BATCHES_POST_01
(
    je_batch_id                bigint not null,  --(OK)
    last_update_date           datetime not null,
    last_updated_by            bigint not null,
    set_of_books_id_11i        bigint,
    name                       VARCHAR(100) not null,  --(OK)
    status                     VARCHAR(1) not null,
    status_verified            VARCHAR(1) not null,
    actual_flag                VARCHAR(1) not null,
    default_effective_date     datetime not null,
    average_journal_flag       VARCHAR(1) not null,
    budgetary_control_status   VARCHAR(1) not null,
    approval_status_code       VARCHAR(1) not null,
    creation_date              datetime,  --(OK)
    created_by                 bigint,  --(OK)
    last_update_login          bigint,
    status_reset_flag          VARCHAR(1),
    default_period_name        VARCHAR(15),  --(OK)
    unique_date                VARCHAR(30),
    earliest_postable_date     datetime,
    posted_date                datetime,  ---(OK)
    date_created               datetime,
    description                VARCHAR(240),
    control_total              bigint,
    running_total_dr           bigint,
    running_total_cr           bigint,
    running_total_accounted_dr bigint,
    running_total_accounted_cr bigint,
    parent_je_batch_id         bigint,
    attribute1                 VARCHAR(150),
    attribute2                 VARCHAR(150),
    attribute3                 VARCHAR(150),
    attribute4                 VARCHAR(150),
    attribute5                 VARCHAR(150),
    attribute6                 VARCHAR(150),
    attribute7                 VARCHAR(150),
    attribute8                 VARCHAR(150),
    attribute9                 VARCHAR(150),
    attribute10                VARCHAR(150),
    context                    VARCHAR(150),
    unreservation_packet_id    bigint,
    packet_id                  bigint,
    ussgl_transaction_code     VARCHAR(30),
    context2                   VARCHAR(150),
    posting_run_id             bigint,
    request_id                 bigint,
    org_id                     bigint,  --(OK)
    posted_by                  bigint,
    chart_of_accounts_id       bigint not null,
    period_set_name            VARCHAR(15) not null,
    accounted_period_type      VARCHAR(15) not null,
    group_id                   bigint,  --(OK)
    approver_employee_id       bigint,
    global_attribute_category  VARCHAR(150),
    global_attribute1          VARCHAR(150),
    global_attribute2          VARCHAR(150),
    global_attribute3          VARCHAR(150),
    global_attribute4          VARCHAR(150),
    global_attribute5          VARCHAR(150),
    global_attribute6          VARCHAR(150),
    global_attribute7          VARCHAR(150),
    global_attribute8          VARCHAR(150),
    global_attribute9          VARCHAR(150),
    global_attribute10         VARCHAR(150),
    global_attribute11         VARCHAR(150),
    global_attribute12         VARCHAR(150),
    global_attribute13         VARCHAR(150),
    global_attribute14         VARCHAR(150),
    global_attribute15         VARCHAR(150),
    global_attribute16         VARCHAR(150),
    global_attribute17         VARCHAR(150),
    global_attribute18         VARCHAR(150),
    global_attribute19         VARCHAR(150),
    global_attribute20         VARCHAR(150),
    ods_creation_date          datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


-- 日记账头表： gl_je_headers
-- Create table
create table GL_JE_HEADERS_POST_01
(
    je_header_id                 bigint not null,  --(OK)
    last_update_date             datetime not null,
    last_updated_by              bigint not null,
    ledger_id                    bigint not null,
    je_category                  VARCHAR(25) not null,  --(OK)
    je_source                    VARCHAR(25) not null,  --(OK)
    period_name                  VARCHAR(15) not null,  --(OK)
    name                         VARCHAR(100) not null,  --(OK)
    currency_code                VARCHAR(15) not null,  --(OK)
    status                       VARCHAR(1) not null,
    date_created                 datetime not null,
    accrual_rev_flag             VARCHAR(1) not null,
    multi_bal_seg_flag           VARCHAR(1) not null,
    actual_flag                  VARCHAR(1) not null,  --(OK)
    default_effective_date       datetime not null,
    tax_status_code              VARCHAR(1) not null,
    conversion_flag              VARCHAR(1),
    creation_date                datetime,
    created_by                   bigint,
    last_update_login            bigint,
    encumbrance_type_id          bigint,
    budget_version_id            bigint,
    balanced_je_flag             VARCHAR(1),
    balancing_segment_value      VARCHAR(25),
    je_batch_id                  bigint,  --(OK)
    from_recurring_header_id     bigint,
    unique_date                  VARCHAR(30),
    earliest_postable_date       datetime,
    posted_date                  datetime,
    accrual_rev_effective_date   datetime,
    accrual_rev_period_name      VARCHAR(15),
    accrual_rev_status           VARCHAR(1),
    accrual_rev_je_header_id     bigint,
    accrual_rev_change_sign_flag VARCHAR(1) not null,
    description                  VARCHAR(240), 
    control_total                bigint,
    running_total_dr             bigint,
    running_total_cr             bigint,
    running_total_accounted_dr   bigint,
    running_total_accounted_cr   bigint,
    currency_conversion_rate     bigint,  --(OK)汇率
    currency_conversion_type     VARCHAR(30),
    currency_conversion_date     datetime,
    external_reference           VARCHAR(80),
    parent_je_header_id          bigint,
    reversed_je_header_id        bigint,
    originating_bal_seg_value    VARCHAR(25),
    intercompany_mode            bigint,
    dr_bal_seg_value             VARCHAR(25),
    cr_bal_seg_value             VARCHAR(25),
    attribute1                   VARCHAR(150),
    attribute2                   VARCHAR(150),
    attribute3                   VARCHAR(150),
    attribute4                   VARCHAR(150),
    attribute5                   VARCHAR(150),
    attribute6                   VARCHAR(150),
    attribute7                   VARCHAR(150),
    attribute8                   VARCHAR(150),
    attribute9                   VARCHAR(150),
    attribute10                  VARCHAR(150),
    context                      VARCHAR(150),
    global_attribute_category    VARCHAR(30),
    global_attribute1            VARCHAR(150),
    global_attribute2            VARCHAR(150),
    global_attribute3            VARCHAR(150),
    global_attribute4            VARCHAR(150),
    global_attribute5            VARCHAR(150),
    global_attribute6            VARCHAR(150),
    global_attribute7            VARCHAR(150),
    global_attribute8            VARCHAR(150),
    global_attribute9            VARCHAR(150),
    global_attribute10           VARCHAR(150),
    ussgl_transaction_code       VARCHAR(30),
    context2                     VARCHAR(150),
    doc_sequence_id              bigint,
    doc_sequence_value           bigint,
    jgzz_recon_context           VARCHAR(30),
    jgzz_recon_ref               VARCHAR(240),
    reference_date               datetime,
    local_doc_sequence_id        bigint,
    local_doc_sequence_value     bigint,
    display_alc_journal_flag     VARCHAR(1),
    je_from_sla_flag             VARCHAR(1),
    posting_acct_seq_version_id  bigint,
    posting_acct_seq_assign_id   bigint,
    posting_acct_seq_value       bigint,
    close_acct_seq_version_id    bigint,
    close_acct_seq_assign_id     bigint,
    close_acct_seq_value         bigint,
    ods_creation_date            datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- 日记账行表：gl_je_lines
-- Create table
create table GL_JE_LINES_POST_01
(
    je_header_id                 bigint not null,  --(OK)
    je_line_num                  bigint not null,  --(OK)
    last_update_date             datetime not null,
    last_updated_by              bigint not null,
    ledger_id                    bigint not null,  --(OK)
    code_combination_id          bigint not null,  --(OK)
    period_name                  VARCHAR(15) not null,  --(OK)
    effective_date               datetime not null,  --(OK)
    status                       VARCHAR(1) not null,
    creation_date                datetime,  --(OK)
    created_by                   bigint,  --(OK)
    last_update_login            bigint,
    entered_dr                   bigint,
    entered_cr                   bigint,
    accounted_dr                 bigint,  --(OK)
    accounted_cr                 bigint,  --(OK)
    description                  VARCHAR(240),  --(OK)
    line_type_code               VARCHAR(20),
    reference_1                  VARCHAR(240),
    reference_2                  VARCHAR(240),
    reference_3                  VARCHAR(240),
    reference_4                  VARCHAR(240),
    reference_5                  VARCHAR(240),
    attribute1                   VARCHAR(150),
    attribute2                   VARCHAR(150),
    attribute3                   VARCHAR(150),
    attribute4                   VARCHAR(150),
    attribute5                   VARCHAR(150),
    attribute6                   VARCHAR(150),
    attribute7                   VARCHAR(150),
    attribute8                   VARCHAR(150),
    attribute9                   VARCHAR(150),
    attribute10                  VARCHAR(150),
    attribute11                  VARCHAR(150),
    attribute12                  VARCHAR(150),
    attribute13                  VARCHAR(150),
    attribute14                  VARCHAR(150),
    attribute15                  VARCHAR(150),
    attribute16                  VARCHAR(150),
    attribute17                  VARCHAR(150),
    attribute18                  VARCHAR(150),
    attribute19                  VARCHAR(150),
    attribute20                  VARCHAR(150),
    context                      VARCHAR(150),
    context2                     VARCHAR(150),
    invoice_date                 datetime,
    tax_code                     VARCHAR(15),
    invoice_identifier           VARCHAR(20),
    invoice_amount               bigint,
    no1                          VARCHAR(150),
    stat_amount                  bigint,
    ignore_rate_flag             VARCHAR(1),
    context3                     VARCHAR(150),
    ussgl_transaction_code       VARCHAR(30),
    subledger_doc_sequence_id    bigint,
    context4                     VARCHAR(150),
    subledger_doc_sequence_value bigint,
    reference_6                  VARCHAR(240),
    reference_7                  VARCHAR(240),
    gl_sl_link_id                bigint,  --(OK)
    gl_sl_link_table             VARCHAR(30),  --(OK)
    reference_8                  VARCHAR(240),
    reference_9                  VARCHAR(240), --(OK)全成本代码+指标
    reference_10                 VARCHAR(240),
    global_attribute_category    VARCHAR(30),
    global_attribute1            VARCHAR(150),
    global_attribute2            VARCHAR(150),
    global_attribute3            VARCHAR(150),
    global_attribute4            VARCHAR(150),
    global_attribute5            VARCHAR(150),
    global_attribute6            VARCHAR(150),
    global_attribute7            VARCHAR(150),
    global_attribute8            VARCHAR(150),
    global_attribute9            VARCHAR(150),
    global_attribute10           VARCHAR(150),
    jgzz_recon_status_11i        VARCHAR(1),
    jgzz_recon_date_11i          datetime,
    jgzz_recon_id_11i            bigint,
    jgzz_recon_ref_11i           VARCHAR(240),
    jgzz_recon_context_11i       VARCHAR(30),
    taxable_line_flag            VARCHAR(1),
    tax_type_code                VARCHAR(1),
    tax_code_id                  bigint,
    tax_rounding_rule_code       VARCHAR(1),
    amount_includes_tax_flag     VARCHAR(1),
    tax_document_identifier      VARCHAR(50),
    tax_document_date            datetime,
    tax_customer_name            VARCHAR(240),
    tax_customer_reference       VARCHAR(240),
    tax_registration_number      VARCHAR(50),
    tax_line_flag                VARCHAR(1),
    tax_group_id                 bigint,
    co_third_party               VARCHAR(14),
    co_processed_flag            VARCHAR(1),
    ods_creation_date            datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- 账户科目段： gl_code_combinations
create table GL_CODE_COMBINATIONS_01
(
    code_combination_id           bigint not null,  --(OK)
    last_update_date              datetime not null,
    last_updated_by               bigint not null,
    chart_of_accounts_id          bigint not null,  --(OK)
    detail_posting_allowed_flag   VARCHAR(1) not null,
    detail_budgeting_allowed_flag VARCHAR(1) not null,
    account_type                  VARCHAR(1) not null,
    enabled_flag                  VARCHAR(1) not null,
    summary_flag                  VARCHAR(1) not null,  --(OK)
    segment1                      VARCHAR(25),  --(OK)
    segment2                      VARCHAR(25),  --(OK)
    segment3                      VARCHAR(25),  --(OK)
    segment4                      VARCHAR(25),  --(OK)
    segment5                      VARCHAR(25),  --(OK)
    segment6                      VARCHAR(25),  --(OK)
    segment7                      VARCHAR(25),  --(OK)
    segment8                      VARCHAR(25),  --(OK)
    segment9                      VARCHAR(25),  --(OK)
    segment10                     VARCHAR(25),
    segment11                     VARCHAR(25),
    segment12                     VARCHAR(25),
    segment13                     VARCHAR(25),
    segment14                     VARCHAR(25),
    segment15                     VARCHAR(25),
    segment16                     VARCHAR(25),
    segment17                     VARCHAR(25),
    segment18                     VARCHAR(25),
    segment19                     VARCHAR(25),
    segment20                     VARCHAR(25),
    segment21                     VARCHAR(25),
    segment22                     VARCHAR(25),
    segment23                     VARCHAR(25),
    segment24                     VARCHAR(25),
    segment25                     VARCHAR(25),
    segment26                     VARCHAR(25),
    segment27                     VARCHAR(25),
    segment28                     VARCHAR(25),
    segment29                     VARCHAR(25),
    segment30                     VARCHAR(25),
    description                   VARCHAR(240),
    template_id                   bigint,
    allocation_create_flag        VARCHAR(1),
    start_date_active             datetime,
    end_date_active               datetime,
    attribute1                    VARCHAR(150),
    attribute2                    VARCHAR(150),
    attribute3                    VARCHAR(150),
    attribute4                    VARCHAR(150),
    attribute5                    VARCHAR(150),
    attribute6                    VARCHAR(150),
    attribute7                    VARCHAR(150),
    attribute8                    VARCHAR(150),
    attribute9                    VARCHAR(150),
    attribute10                   VARCHAR(150),
    context                       VARCHAR(150),
    segment_attribute1            VARCHAR(60),
    segment_attribute2            VARCHAR(60),
    segment_attribute3            VARCHAR(60),
    segment_attribute4            VARCHAR(60),
    segment_attribute5            VARCHAR(60),
    segment_attribute6            VARCHAR(60),
    segment_attribute7            VARCHAR(60),
    segment_attribute8            VARCHAR(60),
    segment_attribute9            VARCHAR(60),
    segment_attribute10           VARCHAR(60),
    segment_attribute11           VARCHAR(60),
    segment_attribute12           VARCHAR(60),
    segment_attribute13           VARCHAR(60),
    segment_attribute14           VARCHAR(60),
    segment_attribute15           VARCHAR(60),
    segment_attribute16           VARCHAR(60),
    segment_attribute17           VARCHAR(60),
    segment_attribute18           VARCHAR(60),
    segment_attribute19           VARCHAR(60),
    segment_attribute20           VARCHAR(60),
    segment_attribute21           VARCHAR(60),
    segment_attribute22           VARCHAR(60),
    segment_attribute23           VARCHAR(60),
    segment_attribute24           VARCHAR(60),
    segment_attribute25           VARCHAR(60),
    segment_attribute26           VARCHAR(60),
    segment_attribute27           VARCHAR(60),
    segment_attribute28           VARCHAR(60),
    segment_attribute29           VARCHAR(60),
    segment_attribute30           VARCHAR(60),
    segment_attribute31           VARCHAR(60),
    segment_attribute32           VARCHAR(60),
    segment_attribute33           VARCHAR(60),
    segment_attribute34           VARCHAR(60),
    segment_attribute35           VARCHAR(60),
    segment_attribute36           VARCHAR(60),
    segment_attribute37           VARCHAR(60),
    segment_attribute38           VARCHAR(60),
    segment_attribute39           VARCHAR(60),
    segment_attribute40           VARCHAR(60),
    segment_attribute41           VARCHAR(60),
    segment_attribute42           VARCHAR(60),
    reference1                    VARCHAR(1),
    reference2                    VARCHAR(1),
    reference3                    VARCHAR(25),
    reference4                    VARCHAR(1),
    reference5                    VARCHAR(1),
    jgzz_recon_flag               VARCHAR(1),
    jgzz_recon_context            VARCHAR(30),
    preserve_flag                 VARCHAR(1),
    refresh_flag                  VARCHAR(1),
    igi_balanced_budget_flag      VARCHAR(1),
    company_cost_center_org_id    bigint,
    revaluation_id                bigint,
    ledger_segment                VARCHAR(20),
    ledger_type_code              VARCHAR(1),
    alternate_code_combination_id bigint,
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- Create table
create table QGL_SEQUENCE_VALUE_01
(
    je_header_id      bigint not null,  --(OK)
    sequence_value    VARCHAR(1000),  --(OK)
    last_update_date  datetime not null,  --(OK)
    ods_creation_date datetime  --(OK)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


create table GL_JE_CATEGORIES_TL_01
(
    je_category_name      VARCHAR(25) not null,  --(OK)
    language              VARCHAR(4) not null,
    source_lang           VARCHAR(4) not null,
    user_je_category_name VARCHAR(25) not null,  --(OK)
    last_update_date      datetime not null,
    last_updated_by       bigint not null,
    creation_date         datetime,
    created_by            bigint,
    last_update_login     bigint,
    description           VARCHAR(240),
    attribute1            VARCHAR(150),
    attribute2            VARCHAR(150),
    attribute3            VARCHAR(150),
    attribute4            VARCHAR(150),
    attribute5            VARCHAR(150),
    context               VARCHAR(150),
    consolidation_flag    VARCHAR(1),
    je_category_key       VARCHAR(25) not null,  --(OK)
    ods_creation_date     datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


-- Create table
create table AP_BATCHES_ALL_01
(
    batch_id                  bigint not null,  --(OK)
    batch_name                VARCHAR(50) not null,  --(OK)
    batch_date                datetime not null,  --(OK)
    last_update_date          datetime not null,
    last_updated_by           bigint not null,
    control_invoice_count     bigint,
    control_invoice_total     bigint,
    actual_invoice_count      bigint,
    actual_invoice_total      bigint,
    invoice_currency_code     VARCHAR(15),
    payment_currency_code     VARCHAR(15),
    last_update_login         bigint,
    creation_date             datetime,  --(OK)
    created_by                bigint,  --(OK)
    pay_group_lookup_code     VARCHAR(25),
    batch_code_combination_id bigint,
    terms_id                  bigint,
    attribute_category        VARCHAR(150),
    attribute1                VARCHAR(150),
    attribute2                VARCHAR(150),
    attribute3                VARCHAR(150),
    attribute4                VARCHAR(150),
    attribute5                VARCHAR(150),
    attribute6                VARCHAR(150),
    attribute7                VARCHAR(150),
    attribute8                VARCHAR(150),
    attribute9                VARCHAR(150),
    attribute10               VARCHAR(150),
    attribute11               VARCHAR(150),
    attribute12               VARCHAR(150),
    attribute13               VARCHAR(150),
    attribute14               VARCHAR(150),
    attribute15               VARCHAR(150),
    invoice_type_lookup_code  VARCHAR(25),
    hold_lookup_code          VARCHAR(25),
    hold_reason               VARCHAR(240),
    doc_category_code         VARCHAR(30),
    org_id                    bigint,  --(OK)
    gl_date                   datetime,  --(OK)
    payment_priority          bigint,
    ods_creation_date         datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;




-- 发票（invoice）头表：ap_invoices(ap_invoices_all)
create table AP_INVOICE_STD_01
(
    invoice_id                    bigint not null,  --(OK)
    last_update_date              datetime not null,
    last_updated_by               bigint not null,
    vendor_id                     bigint,  --(OK)
    invoice_num                   VARCHAR(50) not null,  --(OK)
    set_of_books_id               bigint not null,  --(OK)
    invoice_currency_code         VARCHAR(15) not null,
    payment_currency_code         VARCHAR(15) not null,
    payment_cross_rate            bigint not null,
    invoice_amount                bigint,  --(OK)
    vendor_site_id                bigint,  --(OK)
    amount_paid                   bigint,
    discount_amount_taken         bigint,
    invoice_date                  datetime,  --(OK)
    source                        VARCHAR(25),  --(OK)
    invoice_type_lookup_code      VARCHAR(25),
    description                   VARCHAR(240),  --(OK)
    batch_id                      bigint,  --(OK)
    amount_applicable_to_discount bigint,
    tax_amount                    bigint,
    terms_id                      bigint,
    terms_date                    datetime,
    payment_method_lookup_code    VARCHAR(25),
    pay_group_lookup_code         VARCHAR(25),
    accts_pay_code_combination_id bigint,
    payment_status_flag           VARCHAR(1),
    creation_date                 datetime,
    created_by                    bigint,  --(OK)
    base_amount                   bigint,
    vat_code                      VARCHAR(15),
    last_update_login             bigint,
    exclusive_payment_flag        VARCHAR(1),
    po_header_id                  bigint,
    freight_amount                bigint,
    goods_received_date           datetime,
    invoice_received_date         datetime,
    voucher_num                   VARCHAR(50),
    approved_amount               bigint,
    recurring_payment_id          bigint,
    exchange_rate                 bigint,
    exchange_rate_type            VARCHAR(30),
    exchange_date                 datetime,
    earliest_settlement_date      datetime,
    original_prepayment_amount    bigint,
    doc_sequence_id               bigint,
    doc_sequence_value            bigint,
    doc_category_code             VARCHAR(30),
    attribute1                    VARCHAR(100),
    attribute2                    VARCHAR(100),
    attribute3                    VARCHAR(100),
    attribute4                    VARCHAR(100),  --(OK)
    attribute5                    VARCHAR(100),
    attribute6                    VARCHAR(100),
    attribute7                    VARCHAR(100),
    attribute8                    VARCHAR(100),
    attribute9                    VARCHAR(100),
    attribute10                   VARCHAR(100),
    attribute11                   VARCHAR(100),
    attribute12                   VARCHAR(100),
    attribute13                   VARCHAR(100),
    attribute14                   VARCHAR(100),
    attribute15                   VARCHAR(100),
    attribute_category            VARCHAR(100),
    approval_status               VARCHAR(1000),
    approval_description          VARCHAR(240),
    invoice_distribution_total    bigint,
    posting_status                VARCHAR(15),
    prepay_flag                   VARCHAR(1),
    authorized_by                 VARCHAR(25),
    cancelled_date                datetime,
    cancelled_by                  bigint,
    cancelled_amount              bigint,
    temp_cancelled_amount         bigint,
    project_accounting_context    VARCHAR(30),
    ussgl_transaction_code        VARCHAR(30),
    ussgl_trx_code_context        VARCHAR(30),
    project_id                    bigint,  --(OK)
    task_id                       bigint,  --(OK)
    expenditure_type              VARCHAR(30),
    expenditure_item_date         datetime,
    pa_quantity                   DECIMAL(22,5),
    expenditure_organization_id   bigint,
    pa_default_dist_ccid          bigint,
    vendor_prepay_amount          bigint,
    payment_amount_total          bigint,
    awt_flag                      VARCHAR(1),
    awt_group_id                  bigint,
    reference_1                   VARCHAR(30),
    reference_2                   VARCHAR(30),
    org_id                        bigint,  --(OK)
    pre_withholding_amount        bigint,
    global_attribute_category     VARCHAR(100),
    global_attribute1             VARCHAR(100),
    global_attribute2             VARCHAR(100),
    global_attribute3             VARCHAR(100),
    global_attribute4             VARCHAR(100),
    global_attribute5             VARCHAR(100),
    global_attribute6             VARCHAR(100),
    global_attribute7             VARCHAR(100),
    global_attribute8             VARCHAR(100),
    global_attribute9             VARCHAR(100),
    global_attribute10            VARCHAR(100),
    global_attribute11            VARCHAR(100),
    global_attribute12            VARCHAR(150),
    global_attribute13            VARCHAR(100),
    global_attribute14            VARCHAR(100),
    global_attribute15            VARCHAR(100),
    global_attribute16            VARCHAR(100),
    global_attribute17            VARCHAR(100),
    global_attribute18            VARCHAR(100),
    global_attribute19            VARCHAR(100),
    global_attribute20            VARCHAR(100),
    auto_tax_calc_flag            VARCHAR(1),
    payment_cross_rate_type       VARCHAR(30),
    payment_cross_rate_date       datetime,
    pay_curr_invoice_amount       bigint,
    mrc_base_amount               VARCHAR(1000),
    mrc_exchange_rate             VARCHAR(1000),
    mrc_exchange_rate_type        VARCHAR(1000),
    mrc_exchange_date             VARCHAR(1000),
    gl_date                       datetime not null,
    award_id                      bigint,
    paid_on_behalf_employee_id    bigint,
    amt_due_ccard_company         bigint,
    amt_due_employee              bigint,
    approval_ready_flag           VARCHAR(1) not null,
    approval_iteration            bigint,
    wfapproval_status             VARCHAR(50) not null,
    requester_id                  bigint,
    validation_request_id         bigint,
    validated_tax_amount          bigint,
    quick_credit                  VARCHAR(1),
    credited_invoice_id           bigint,
    distribution_set_id           bigint,
    application_id                bigint,
    product_table                 VARCHAR(30),
    reference_key1                VARCHAR(100),
    reference_key2                VARCHAR(100),
    reference_key3                VARCHAR(100),
    reference_key4                VARCHAR(100),
    reference_key5                VARCHAR(100),
    total_tax_amount              bigint,
    self_assessed_tax_amount      bigint,
    tax_related_invoice_id        bigint,
    trx_business_category         VARCHAR(240),
    user_defined_fisc_class       VARCHAR(240),
    taxation_country              VARCHAR(30),
    document_sub_type             VARCHAR(100),
    supplier_tax_invoice_number   VARCHAR(100),
    supplier_tax_invoice_date     datetime,
    supplier_tax_exchange_rate    bigint,
    tax_invoice_recording_date    datetime,
    tax_invoice_internal_seq      VARCHAR(100),
    legal_entity_id               bigint,
    historical_flag               VARCHAR(1),
    force_revalidation_flag       VARCHAR(1),
    bank_charge_bearer            VARCHAR(30),
    remittance_message1           VARCHAR(100),
    remittance_message2           VARCHAR(100),
    remittance_message3           VARCHAR(100),
    unique_remittance_identifier  VARCHAR(30),
    uri_check_digit               VARCHAR(2),
    settlement_priority           VARCHAR(30),
    payment_reason_code           VARCHAR(30),
    payment_reason_comments       VARCHAR(240),
    payment_method_code           VARCHAR(30),
    delivery_channel_code         VARCHAR(30),
    quick_po_header_id            bigint,
    net_of_retainage_flag         VARCHAR(1),
    release_amount_net_of_tax     bigint,
    control_amount                bigint,
    party_id                      bigint,
    party_site_id                 bigint,
    pay_proc_trxn_type_code       VARCHAR(30),
    payment_function              VARCHAR(30),
    cust_registration_code        VARCHAR(50),
    cust_registration_number      VARCHAR(30),
    port_of_entry_code            VARCHAR(30),
    external_bank_account_id      bigint,
    vendor_contact_id             bigint,
    internal_contact_email        VARCHAR(1000),
    disc_is_inv_less_tax_flag     VARCHAR(1),
    exclude_freight_from_discount VARCHAR(1),
    pay_awt_group_id              bigint,
    original_invoice_amount       bigint,
    dispute_reason                VARCHAR(100),
    remit_to_supplier_name        VARCHAR(240),
    remit_to_supplier_id          bigint,
    remit_to_supplier_site        VARCHAR(240),
    remit_to_supplier_site_id     bigint,
    relationship_id               bigint,
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- 预付款(同AP_INVOICE_STD_01表)
CREATE TABLE ap_invoice_pre_01
(
    invoice_id bigint NOT NULL,
    last_update_date DATETIME NOT NULL,
    last_updated_by bigint NOT NULL,
    vendor_id bigint,
    invoice_num VARCHAR(50) NOT NULL,
    set_of_books_id bigint NOT NULL,
    invoice_currency_code VARCHAR(15) NOT NULL,
    payment_currency_code VARCHAR(15) NOT NULL,
    payment_cross_rate bigint NOT NULL,
    invoice_amount bigint,
    vendor_site_id bigint,
    amount_paid bigint,
    discount_amount_taken bigint,
    invoice_date DATETIME,
    source VARCHAR(25),
    invoice_type_lookup_code VARCHAR(25),
    description VARCHAR(240),
    batch_id bigint,
    amount_applicable_to_discount bigint,
    tax_amount bigint,
    terms_id bigint,
    terms_date DATETIME,
    payment_method_lookup_code VARCHAR(25),
    pay_group_lookup_code VARCHAR(25),
    accts_pay_code_combination_id bigint,
    payment_status_flag VARCHAR(1),
    creation_date DATETIME,
    created_by bigint,
    base_amount bigint,
    vat_code VARCHAR(15),
    last_update_login bigint,
    exclusive_payment_flag VARCHAR(1),
    po_header_id bigint,
    freight_amount bigint,
    goods_received_date DATETIME,
    invoice_received_date DATETIME,
    voucher_num VARCHAR(50),
    approved_amount bigint,
    recurring_payment_id bigint,
    exchange_rate bigint,
    exchange_rate_type VARCHAR(30),
    exchange_date DATETIME,
    earliest_settlement_date DATETIME,
    original_prepayment_amount bigint,
    doc_sequence_id bigint,
    doc_sequence_value bigint,
    doc_category_code VARCHAR(30),
    attribute1 VARCHAR(100),
    attribute2 VARCHAR(100),
    attribute3 VARCHAR(100),
    attribute4 VARCHAR(100),
    attribute5 VARCHAR(100),
    attribute6 VARCHAR(100),
    attribute7 VARCHAR(100),
    attribute8 VARCHAR(100),
    attribute9 VARCHAR(100),
    attribute10 VARCHAR(100),
    attribute11 VARCHAR(100),
    attribute12 VARCHAR(100),
    attribute13 VARCHAR(100),
    attribute14 VARCHAR(100),
    attribute15 VARCHAR(100),
    attribute_category VARCHAR(100),
    approval_status VARCHAR(1000),
    approval_description VARCHAR(240),
    invoice_distribution_total bigint,
    posting_status VARCHAR(15),
    prepay_flag VARCHAR(1),
    authorized_by VARCHAR(25),
    cancelled_date DATETIME,
    cancelled_by bigint,
    cancelled_amount bigint,
    temp_cancelled_amount bigint,
    project_accounting_context VARCHAR(30),
    ussgl_transaction_code VARCHAR(30),
    ussgl_trx_code_context VARCHAR(30),
    project_id bigint,
    task_id bigint,
    expenditure_type VARCHAR(30),
    expenditure_item_date DATETIME,
    pa_quantity DECIMAL(22,5),
    expenditure_organization_id bigint,
    pa_default_dist_ccid bigint,
    vendor_prepay_amount bigint,
    payment_amount_total bigint,
    awt_flag VARCHAR(1),
    awt_group_id bigint,
    reference_1 VARCHAR(30),
    reference_2 VARCHAR(30),
    org_id bigint,
    pre_withholding_amount bigint,
    global_attribute_category VARCHAR(100),
    global_attribute1 VARCHAR(100),
    global_attribute2 VARCHAR(100),
    global_attribute3 VARCHAR(100),
    global_attribute4 VARCHAR(100),
    global_attribute5 VARCHAR(100),
    global_attribute6 VARCHAR(100),
    global_attribute7 VARCHAR(100),
    global_attribute8 VARCHAR(100),
    global_attribute9 VARCHAR(100),
    global_attribute10 VARCHAR(100),
    global_attribute11 VARCHAR(100),
    global_attribute12 VARCHAR(150),
    global_attribute13 VARCHAR(100),
    global_attribute14 VARCHAR(100),
    global_attribute15 VARCHAR(100),
    global_attribute16 VARCHAR(100),
    global_attribute17 VARCHAR(100),
    global_attribute18 VARCHAR(100),
    global_attribute19 VARCHAR(100),
    global_attribute20 VARCHAR(100),
    auto_tax_calc_flag VARCHAR(1),
    payment_cross_rate_type VARCHAR(30),
    payment_cross_rate_date DATETIME,
    pay_curr_invoice_amount bigint,
    mrc_base_amount VARCHAR(1000),
    mrc_exchange_rate VARCHAR(1000),
    mrc_exchange_rate_type VARCHAR(1000),
    mrc_exchange_date VARCHAR(1000),
    gl_date DATETIME NOT NULL,
    award_id bigint,
    paid_on_behalf_employee_id bigint,
    amt_due_ccard_company bigint,
    amt_due_employee bigint,
    approval_ready_flag VARCHAR(1) NOT NULL,
    approval_iteration bigint,
    wfapproval_status VARCHAR(50) NOT NULL,
    requester_id bigint,
    validation_request_id bigint,
    validated_tax_amount bigint,
    quick_credit VARCHAR(1),
    credited_invoice_id bigint,
    distribution_set_id bigint,
    application_id bigint,
    product_table VARCHAR(30),
    reference_key1 VARCHAR(100),
    reference_key2 VARCHAR(100),
    reference_key3 VARCHAR(100),
    reference_key4 VARCHAR(100),
    reference_key5 VARCHAR(100),
    total_tax_amount bigint,
    self_assessed_tax_amount bigint,
    tax_related_invoice_id bigint,
    trx_business_category VARCHAR(240),
    user_defined_fisc_class VARCHAR(240),
    taxation_country VARCHAR(30),
    document_sub_type VARCHAR(100),
    supplier_tax_invoice_number VARCHAR(100),
    supplier_tax_invoice_date DATETIME,
    supplier_tax_exchange_rate bigint,
    tax_invoice_recording_date DATETIME,
    tax_invoice_internal_seq VARCHAR(100),
    legal_entity_id bigint,
    historical_flag VARCHAR(1),
    force_revalidation_flag VARCHAR(1),
    bank_charge_bearer VARCHAR(30),
    remittance_message1 VARCHAR(100),
    remittance_message2 VARCHAR(100),
    remittance_message3 VARCHAR(100),
    unique_remittance_identifier VARCHAR(30),
    uri_check_digit VARCHAR(2),
    settlement_priority VARCHAR(30),
    payment_reason_code VARCHAR(30),
    payment_reason_comments VARCHAR(240),
    payment_method_code VARCHAR(30),
    delivery_channel_code VARCHAR(30),
    quick_po_header_id bigint,
    net_of_retainage_flag VARCHAR(1),
    release_amount_net_of_tax bigint,
    control_amount bigint,
    party_id bigint,
    party_site_id bigint,
    pay_proc_trxn_type_code VARCHAR(30),
    payment_function VARCHAR(30),
    cust_registration_code VARCHAR(50),
    cust_registration_number VARCHAR(30),
    port_of_entry_code VARCHAR(30),
    external_bank_account_id bigint,
    vendor_contact_id bigint,
    internal_contact_email VARCHAR(1000),
    disc_is_inv_less_tax_flag VARCHAR(1),
    exclude_freight_from_discount VARCHAR(1),
    pay_awt_group_id bigint,
    original_invoice_amount bigint,
    dispute_reason VARCHAR(100),
    remit_to_supplier_name VARCHAR(240),
    remit_to_supplier_id bigint,
    remit_to_supplier_site VARCHAR(240),
    remit_to_supplier_site_id bigint,
    relationship_id bigint,
    ods_creation_date DATETIME
)
    ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 发票（invoice）分配行表：ap_invoice_distributions_all
create table AP_INVOICE_DIST_STD_01
(
    accounting_date               datetime not null,
    accrual_posted_flag           VARCHAR(1),
    assets_addition_flag          VARCHAR(1) not null,
    assets_tracking_flag          VARCHAR(1) not null,
    cash_posted_flag              VARCHAR(1),
    distribution_line_number      bigint not null,
    dist_code_combination_id      bigint not null,
    invoice_id                    bigint not null,
    last_updated_by               bigint not null,
    last_update_date              datetime not null,
    line_type_lookup_code         VARCHAR(25) not null,
    period_name                   VARCHAR(15) not null,
    set_of_books_id               bigint not null,
    accts_pay_code_combination_id bigint,
    amount                        bigint,
    base_amount                   bigint,
    base_invoice_price_variance   bigint,
    batch_id                      bigint,
    created_by                    bigint,
    creation_date                 datetime,
    description                   VARCHAR(240),
    exchange_rate_variance        bigint,
    final_match_flag              VARCHAR(1),
    income_tax_region             VARCHAR(10),
    invoice_price_variance        bigint,
    last_update_login             bigint,
    match_status_flag             VARCHAR(1),
    posted_flag                   VARCHAR(1),
    po_distribution_id            bigint,
    program_application_id        bigint,
    program_id                    bigint,
    program_update_date           datetime,
    quantity_invoiced             bigint,
    rate_var_code_combination_id  bigint,
    request_id                    bigint,
    reversal_flag                 VARCHAR(1),
    type_1099                     VARCHAR(10),
    unit_price                    bigint,
    amount_encumbered             bigint,
    base_amount_encumbered        bigint,
    encumbered_flag               VARCHAR(1),
    exchange_date                 datetime,
    exchange_rate                 bigint,
    exchange_rate_type            VARCHAR(30),
    price_adjustment_flag         VARCHAR(1),
    price_var_code_combination_id bigint,
    quantity_unencumbered         bigint,
    stat_amount                   bigint,
    amount_to_post                bigint,
    attribute1                    VARCHAR(100),
    attribute10                   VARCHAR(100),
    attribute11                   VARCHAR(100),
    attribute12                   VARCHAR(100),
    attribute13                   VARCHAR(100),
    attribute14                   VARCHAR(100),
    attribute15                   VARCHAR(100),
    attribute2                    VARCHAR(100),
    attribute3                    VARCHAR(100),
    attribute4                    VARCHAR(100),
    attribute5                    VARCHAR(100),
    attribute6                    VARCHAR(100),
    attribute7                    VARCHAR(100),
    attribute8                    VARCHAR(100),
    attribute9                    VARCHAR(100),
    attribute_category            VARCHAR(100),
    base_amount_to_post           bigint,
    cash_je_batch_id              bigint,
    expenditure_item_date         datetime,
    expenditure_organization_id   bigint,
    expenditure_type              VARCHAR(30),
    je_batch_id                   bigint,
    parent_invoice_id             bigint,
    pa_addition_flag              VARCHAR(1),
    pa_quantity                   DECIMAL(22,5),
    posted_amount                 bigint,
    posted_base_amount            bigint,
    prepay_amount_remaining       bigint,
    project_accounting_context    VARCHAR(30),
    project_id                    bigint,
    task_id                       bigint,
    ussgl_transaction_code        VARCHAR(30),
    ussgl_trx_code_context        VARCHAR(30),
    earliest_settlement_date      datetime,
    req_distribution_id           bigint,
    quantity_variance             bigint,
    base_quantity_variance        bigint,
    packet_id                     bigint,
    awt_flag                      VARCHAR(1),
    awt_group_id                  bigint,
    awt_tax_rate_id               bigint,
    awt_gross_amount              bigint,
    awt_invoice_id                bigint,
    awt_origin_group_id           bigint,
    reference_1                   VARCHAR(30),
    reference_2                   VARCHAR(30),
    org_id                        bigint,
    other_invoice_id              bigint,
    awt_invoice_payment_id        bigint,
    global_attribute_category     VARCHAR(150),
    global_attribute1             VARCHAR(100),
    global_attribute2             VARCHAR(100),
    global_attribute3             VARCHAR(100),
    global_attribute4             VARCHAR(100),
    global_attribute5             VARCHAR(100),
    global_attribute6             VARCHAR(100),
    global_attribute7             VARCHAR(100),
    global_attribute8             VARCHAR(100),
    global_attribute9             VARCHAR(100),
    global_attribute10            VARCHAR(100),
    global_attribute11            VARCHAR(100),
    global_attribute12            VARCHAR(100),
    global_attribute13            VARCHAR(100),
    global_attribute14            VARCHAR(100),
    global_attribute15            VARCHAR(100),
    global_attribute16            VARCHAR(100),
    global_attribute17            VARCHAR(100),
    global_attribute18            VARCHAR(100),
    global_attribute19            VARCHAR(100),
    global_attribute20            VARCHAR(100),
    line_group_number             bigint,
    receipt_verified_flag         VARCHAR(1),
    receipt_required_flag         VARCHAR(1),
    receipt_missing_flag          VARCHAR(1),
    justification                 VARCHAR(150),
    expense_group                 VARCHAR(80),
    start_expense_date            datetime,
    end_expense_date              datetime,
    receipt_currency_code         VARCHAR(15),
    receipt_conversion_rate       bigint,
    receipt_currency_amount       bigint,
    daily_amount                  bigint,
    web_parameter_id              bigint,
    adjustment_reason             VARCHAR(240),
    award_id                      bigint,
    mrc_accrual_posted_flag       VARCHAR(300),
    mrc_cash_posted_flag          VARCHAR(300),
    mrc_dist_code_combination_id  VARCHAR(300),
    mrc_amount                    VARCHAR(300),
    mrc_base_amount               VARCHAR(300),
    mrc_base_inv_price_variance   VARCHAR(300),
    mrc_exchange_rate_variance    VARCHAR(300),
    mrc_posted_flag               VARCHAR(300),
    mrc_program_application_id    VARCHAR(500),
    mrc_program_id                VARCHAR(500),
    mrc_program_update_date       VARCHAR(500),
    mrc_rate_var_ccid             VARCHAR(500),
    mrc_request_id                VARCHAR(500),
    mrc_exchange_date             VARCHAR(500),
    mrc_exchange_rate             VARCHAR(500),
    mrc_exchange_rate_type        VARCHAR(500),
    mrc_amount_to_post            VARCHAR(500),
    mrc_base_amount_to_post       VARCHAR(500),
    mrc_cash_je_batch_id          VARCHAR(500),
    mrc_je_batch_id               VARCHAR(500),
    mrc_posted_amount             VARCHAR(500),
    mrc_posted_base_amount        VARCHAR(500),
    mrc_receipt_conversion_rate   VARCHAR(500),
    credit_card_trx_id            bigint,
    dist_match_type               VARCHAR(25),
    rcv_transaction_id            bigint,
    invoice_distribution_id       bigint not null,
    parent_reversal_id            bigint,
    tax_recoverable_flag          VARCHAR(1),
    pa_cc_ar_invoice_id           bigint,
    pa_cc_ar_invoice_line_num     bigint,
    pa_cc_processed_code          VARCHAR(1),
    merchant_document_number      VARCHAR(80),
    merchant_name                 VARCHAR(80),
    merchant_reference            VARCHAR(240),
    merchant_tax_reg_number       VARCHAR(80),
    merchant_taxpayer_id          VARCHAR(80),
    country_of_supply             VARCHAR(5),
    matched_uom_lookup_code       VARCHAR(25),
    gms_burdenable_raw_cost       DECIMAL(22,5),
    accounting_event_id           bigint,
    prepay_distribution_id        bigint,
    upgrade_posted_amt            bigint,
    upgrade_base_posted_amt       bigint,
    inventory_transfer_status     VARCHAR(1),
    company_prepaid_invoice_id    bigint,
    cc_reversal_flag              VARCHAR(1),
    awt_withheld_amt              bigint,
    invoice_includes_prepay_flag  VARCHAR(1),
    price_correct_inv_id          bigint,
    price_correct_qty             bigint,
    pa_cmt_xface_flag             VARCHAR(1),
    cancellation_flag             VARCHAR(1),
    invoice_line_number           bigint,
    corrected_invoice_dist_id     bigint,
    rounding_amt                  bigint,
    charge_applicable_to_dist_id  bigint,
    corrected_quantity            bigint,
    related_id                    bigint,
    asset_book_type_code          VARCHAR(15),
    asset_category_id             bigint,
    distribution_class            VARCHAR(30),
    final_payment_rounding        bigint,
    final_application_rounding    bigint,
    amount_at_prepay_xrate        bigint,
    cash_basis_final_app_rounding bigint,
    amount_at_prepay_pay_xrate    bigint,
    intended_use                  VARCHAR(30),
    detail_tax_dist_id            bigint,
    rec_nrec_rate                 bigint,
    recovery_rate_id              bigint,
    recovery_rate_name            VARCHAR(150),
    recovery_type_code            VARCHAR(30),
    recovery_rate_code            VARCHAR(30),
    withholding_tax_code_id       bigint,
    tax_already_distributed_flag  VARCHAR(1),
    summary_tax_line_id           bigint,
    taxable_amount                bigint,
    taxable_base_amount           bigint,
    extra_po_erv                  bigint,
    prepay_tax_diff_amount        bigint,
    tax_code_id                   bigint,
    vat_code                      VARCHAR(15),
    amount_includes_tax_flag      VARCHAR(1),
    tax_calculated_flag           VARCHAR(1),
    tax_recovery_rate             bigint,
    tax_recovery_override_flag    VARCHAR(1),
    tax_code_override_flag        VARCHAR(1),
    total_dist_amount             bigint,
    total_dist_base_amount        bigint,
    prepay_tax_parent_id          bigint,
    cancelled_flag                VARCHAR(1),
    old_distribution_id           bigint,
    old_dist_line_number          bigint,
    amount_variance               bigint,
    base_amount_variance          bigint,
    historical_flag               VARCHAR(1),
    rcv_charge_addition_flag      VARCHAR(1),
    awt_related_id                bigint,
    related_retainage_dist_id     bigint,
    retained_amount_remaining     bigint,
    bc_event_id                   bigint,
    retained_invoice_dist_id      bigint,
    final_release_rounding        bigint,
    fully_paid_acctd_flag         VARCHAR(1),
    root_distribution_id          bigint,
    xinv_parent_reversal_id       bigint,
    recurring_payment_id          bigint,
    release_inv_dist_derived_from bigint,
    pay_awt_group_id              bigint,
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


-- 发票（invoice）预付款 分配行表：ap_invoice_distributions_all
create table AP_INVOICE_DIST_pre_01
(
    accounting_date               datetime not null,
    accrual_posted_flag           VARCHAR(1),
    assets_addition_flag          VARCHAR(1) not null,
    assets_tracking_flag          VARCHAR(1) not null,
    cash_posted_flag              VARCHAR(1),
    distribution_line_number      bigint not null,
    dist_code_combination_id      bigint not null,
    invoice_id                    bigint not null,
    last_updated_by               bigint not null,
    last_update_date              datetime not null,
    line_type_lookup_code         VARCHAR(25) not null,
    period_name                   VARCHAR(15) not null,
    set_of_books_id               bigint not null,
    accts_pay_code_combination_id bigint,
    amount                        bigint,
    base_amount                   bigint,
    base_invoice_price_variance   bigint,
    batch_id                      bigint,
    created_by                    bigint,
    creation_date                 datetime,
    description                   VARCHAR(240),
    exchange_rate_variance        bigint,
    final_match_flag              VARCHAR(1),
    income_tax_region             VARCHAR(10),
    invoice_price_variance        bigint,
    last_update_login             bigint,
    match_status_flag             VARCHAR(1),
    posted_flag                   VARCHAR(1),
    po_distribution_id            bigint,
    program_application_id        bigint,
    program_id                    bigint,
    program_update_date           datetime,
    quantity_invoiced             bigint,
    rate_var_code_combination_id  bigint,
    request_id                    bigint,
    reversal_flag                 VARCHAR(1),
    type_1099                     VARCHAR(10),
    unit_price                    bigint,
    amount_encumbered             bigint,
    base_amount_encumbered        bigint,
    encumbered_flag               VARCHAR(1),
    exchange_date                 datetime,
    exchange_rate                 bigint,
    exchange_rate_type            VARCHAR(30),
    price_adjustment_flag         VARCHAR(1),
    price_var_code_combination_id bigint,
    quantity_unencumbered         bigint,
    stat_amount                   bigint,
    amount_to_post                bigint,
    attribute1                    VARCHAR(100),
    attribute10                   VARCHAR(100),
    attribute11                   VARCHAR(100),
    attribute12                   VARCHAR(100),
    attribute13                   VARCHAR(100),
    attribute14                   VARCHAR(100),
    attribute15                   VARCHAR(100),
    attribute2                    VARCHAR(100),
    attribute3                    VARCHAR(100),
    attribute4                    VARCHAR(100),
    attribute5                    VARCHAR(100),
    attribute6                    VARCHAR(100),
    attribute7                    VARCHAR(100),
    attribute8                    VARCHAR(100),
    attribute9                    VARCHAR(100),
    attribute_category            VARCHAR(100),
    base_amount_to_post           bigint,
    cash_je_batch_id              bigint,
    expenditure_item_date         datetime,
    expenditure_organization_id   bigint,
    expenditure_type              VARCHAR(30),
    je_batch_id                   bigint,
    parent_invoice_id             bigint,
    pa_addition_flag              VARCHAR(1),
    pa_quantity                   DECIMAL(22,5),
    posted_amount                 bigint,
    posted_base_amount            bigint,
    prepay_amount_remaining       bigint,
    project_accounting_context    VARCHAR(30),
    project_id                    bigint,
    task_id                       bigint,
    ussgl_transaction_code        VARCHAR(30),
    ussgl_trx_code_context        VARCHAR(30),
    earliest_settlement_date      datetime,
    req_distribution_id           bigint,
    quantity_variance             bigint,
    base_quantity_variance        bigint,
    packet_id                     bigint,
    awt_flag                      VARCHAR(1),
    awt_group_id                  bigint,
    awt_tax_rate_id               bigint,
    awt_gross_amount              bigint,
    awt_invoice_id                bigint,
    awt_origin_group_id           bigint,
    reference_1                   VARCHAR(30),
    reference_2                   VARCHAR(30),
    org_id                        bigint,
    other_invoice_id              bigint,
    awt_invoice_payment_id        bigint,
    global_attribute_category     VARCHAR(150),
    global_attribute1             VARCHAR(100),
    global_attribute2             VARCHAR(100),
    global_attribute3             VARCHAR(100),
    global_attribute4             VARCHAR(100),
    global_attribute5             VARCHAR(100),
    global_attribute6             VARCHAR(100),
    global_attribute7             VARCHAR(100),
    global_attribute8             VARCHAR(100),
    global_attribute9             VARCHAR(100),
    global_attribute10            VARCHAR(100),
    global_attribute11            VARCHAR(100),
    global_attribute12            VARCHAR(100),
    global_attribute13            VARCHAR(100),
    global_attribute14            VARCHAR(100),
    global_attribute15            VARCHAR(100),
    global_attribute16            VARCHAR(100),
    global_attribute17            VARCHAR(100),
    global_attribute18            VARCHAR(100),
    global_attribute19            VARCHAR(100),
    global_attribute20            VARCHAR(100),
    line_group_number             bigint,
    receipt_verified_flag         VARCHAR(1),
    receipt_required_flag         VARCHAR(1),
    receipt_missing_flag          VARCHAR(1),
    justification                 VARCHAR(150),
    expense_group                 VARCHAR(80),
    start_expense_date            datetime,
    end_expense_date              datetime,
    receipt_currency_code         VARCHAR(15),
    receipt_conversion_rate       bigint,
    receipt_currency_amount       bigint,
    daily_amount                  bigint,
    web_parameter_id              bigint,
    adjustment_reason             VARCHAR(240),
    award_id                      bigint,
    mrc_accrual_posted_flag       VARCHAR(300),
    mrc_cash_posted_flag          VARCHAR(300),
    mrc_dist_code_combination_id  VARCHAR(300),
    mrc_amount                    VARCHAR(300),
    mrc_base_amount               VARCHAR(300),
    mrc_base_inv_price_variance   VARCHAR(300),
    mrc_exchange_rate_variance    VARCHAR(300),
    mrc_posted_flag               VARCHAR(300),
    mrc_program_application_id    VARCHAR(500),
    mrc_program_id                VARCHAR(500),
    mrc_program_update_date       VARCHAR(500),
    mrc_rate_var_ccid             VARCHAR(500),
    mrc_request_id                VARCHAR(500),
    mrc_exchange_date             VARCHAR(500),
    mrc_exchange_rate             VARCHAR(500),
    mrc_exchange_rate_type        VARCHAR(500),
    mrc_amount_to_post            VARCHAR(500),
    mrc_base_amount_to_post       VARCHAR(500),
    mrc_cash_je_batch_id          VARCHAR(500),
    mrc_je_batch_id               VARCHAR(500),
    mrc_posted_amount             VARCHAR(500),
    mrc_posted_base_amount        VARCHAR(500),
    mrc_receipt_conversion_rate   VARCHAR(500),
    credit_card_trx_id            bigint,
    dist_match_type               VARCHAR(25),
    rcv_transaction_id            bigint,
    invoice_distribution_id       bigint not null,
    parent_reversal_id            bigint,
    tax_recoverable_flag          VARCHAR(1),
    pa_cc_ar_invoice_id           bigint,
    pa_cc_ar_invoice_line_num     bigint,
    pa_cc_processed_code          VARCHAR(1),
    merchant_document_number      VARCHAR(80),
    merchant_name                 VARCHAR(80),
    merchant_reference            VARCHAR(240),
    merchant_tax_reg_number       VARCHAR(80),
    merchant_taxpayer_id          VARCHAR(80),
    country_of_supply             VARCHAR(5),
    matched_uom_lookup_code       VARCHAR(25),
    gms_burdenable_raw_cost       DECIMAL(22,5),
    accounting_event_id           bigint,
    prepay_distribution_id        bigint,
    upgrade_posted_amt            bigint,
    upgrade_base_posted_amt       bigint,
    inventory_transfer_status     VARCHAR(1),
    company_prepaid_invoice_id    bigint,
    cc_reversal_flag              VARCHAR(1),
    awt_withheld_amt              bigint,
    invoice_includes_prepay_flag  VARCHAR(1),
    price_correct_inv_id          bigint,
    price_correct_qty             bigint,
    pa_cmt_xface_flag             VARCHAR(1),
    cancellation_flag             VARCHAR(1),
    invoice_line_number           bigint,
    corrected_invoice_dist_id     bigint,
    rounding_amt                  bigint,
    charge_applicable_to_dist_id  bigint,
    corrected_quantity            bigint,
    related_id                    bigint,
    asset_book_type_code          VARCHAR(15),
    asset_category_id             bigint,
    distribution_class            VARCHAR(30),
    final_payment_rounding        bigint,
    final_application_rounding    bigint,
    amount_at_prepay_xrate        bigint,
    cash_basis_final_app_rounding bigint,
    amount_at_prepay_pay_xrate    bigint,
    intended_use                  VARCHAR(30),
    detail_tax_dist_id            bigint,
    rec_nrec_rate                 bigint,
    recovery_rate_id              bigint,
    recovery_rate_name            VARCHAR(150),
    recovery_type_code            VARCHAR(30),
    recovery_rate_code            VARCHAR(30),
    withholding_tax_code_id       bigint,
    tax_already_distributed_flag  VARCHAR(1),
    summary_tax_line_id           bigint,
    taxable_amount                bigint,
    taxable_base_amount           bigint,
    extra_po_erv                  bigint,
    prepay_tax_diff_amount        bigint,
    tax_code_id                   bigint,
    vat_code                      VARCHAR(15),
    amount_includes_tax_flag      VARCHAR(1),
    tax_calculated_flag           VARCHAR(1),
    tax_recovery_rate             bigint,
    tax_recovery_override_flag    VARCHAR(1),
    tax_code_override_flag        VARCHAR(1),
    total_dist_amount             bigint,
    total_dist_base_amount        bigint,
    prepay_tax_parent_id          bigint,
    cancelled_flag                VARCHAR(1),
    old_distribution_id           bigint,
    old_dist_line_number          bigint,
    amount_variance               bigint,
    base_amount_variance          bigint,
    historical_flag               VARCHAR(1),
    rcv_charge_addition_flag      VARCHAR(1),
    awt_related_id                bigint,
    related_retainage_dist_id     bigint,
    retained_amount_remaining     bigint,
    bc_event_id                   bigint,
    retained_invoice_dist_id      bigint,
    final_release_rounding        bigint,
    fully_paid_acctd_flag         VARCHAR(1),
    root_distribution_id          bigint,
    xinv_parent_reversal_id       bigint,
    recurring_payment_id          bigint,
    release_inv_dist_derived_from bigint,
    pay_awt_group_id              bigint,
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- 采购供应商地点表：po_vendor_sites_all
create table PO_VENDOR_SITES_ALL_01
(
    address_style                 VARCHAR(30),
    language                      VARCHAR(30),
    province                      VARCHAR(60),
    country                       VARCHAR(50),
    area_code                     VARCHAR(10),
    phone                         VARCHAR(15),
    customer_num                  VARCHAR(25),
    ship_to_location_id           bigint,
    bill_to_location_id           bigint,
    ship_via_lookup_code          VARCHAR(25),
    freight_terms_lookup_code     VARCHAR(25),
    fob_lookup_code               VARCHAR(25),
    inactive_date                 datetime,
    fax                           VARCHAR(15),
    fax_area_code                 VARCHAR(10),
    telex                         VARCHAR(15),
    terms_date_basis              VARCHAR(25),
    distribution_set_id           bigint,
    accts_pay_code_combination_id bigint,
    prepay_code_combination_id    bigint,
    pay_group_lookup_code         VARCHAR(25),
    payment_priority              bigint,
    terms_id                      bigint,
    invoice_amount_limit          bigint,
    pay_date_basis_lookup_code    VARCHAR(25),
    always_take_disc_flag         VARCHAR(1),
    invoice_currency_code         VARCHAR(15),
    payment_currency_code         VARCHAR(15),
    county                        VARCHAR(60),
    vendor_site_id                bigint not null,
    last_update_date              datetime not null,
    last_updated_by               bigint not null,
    vendor_id                     bigint not null,
    vendor_site_code              VARCHAR(15) not null,
    vendor_site_code_alt          VARCHAR(320),
    last_update_login             bigint,
    creation_date                 datetime not null,
    created_by                    bigint not null,
    purchasing_site_flag          VARCHAR(1),
    rfq_only_site_flag            VARCHAR(1),
    pay_site_flag                 VARCHAR(1),
    attention_ar_flag             VARCHAR(1),
    address_line1                 VARCHAR(240),
    address_line2                 VARCHAR(240),
    address_line3                 VARCHAR(240),
    address_lines_alt             VARCHAR(560),
    city                          VARCHAR(60),
    state                         VARCHAR(60),
    zip                           VARCHAR(40),
    hold_all_payments_flag        VARCHAR(1),
    hold_future_payments_flag     VARCHAR(1),
    hold_reason                   VARCHAR(240),
    hold_unmatched_invoices_flag  VARCHAR(1),
    tax_reporting_site_flag       VARCHAR(1),
    attribute_category            VARCHAR(30),
    attribute1                    VARCHAR(150),
    attribute2                    VARCHAR(150),
    attribute3                    VARCHAR(150),
    attribute4                    VARCHAR(150),
    attribute5                    VARCHAR(150),
    attribute6                    VARCHAR(150),
    attribute7                    VARCHAR(150),
    attribute8                    VARCHAR(150),
    attribute9                    VARCHAR(150),
    attribute10                   VARCHAR(150),
    attribute11                   VARCHAR(150),
    attribute12                   VARCHAR(150),
    attribute13                   VARCHAR(150),
    attribute14                   VARCHAR(150),
    attribute15                   VARCHAR(150),
    request_id                    bigint,
    program_application_id        bigint,
    program_id                    bigint,
    program_update_date           datetime,
    validation_number             bigint,
    exclude_freight_from_discount VARCHAR(1),
    bank_charge_bearer            VARCHAR(1),
    org_id                        bigint,
    check_digits                  VARCHAR(30),
    address_line4                 VARCHAR(240),
    allow_awt_flag                VARCHAR(1),
    awt_group_id                  bigint,
    pay_awt_group_id              bigint,
    default_pay_site_id           bigint,
    pay_on_code                   VARCHAR(25),
    pay_on_receipt_summary_code   VARCHAR(25),
    global_attribute_category     VARCHAR(30),
    global_attribute1             VARCHAR(150),
    global_attribute2             VARCHAR(150),
    global_attribute3             VARCHAR(150),
    global_attribute4             VARCHAR(150),
    global_attribute5             VARCHAR(150),
    global_attribute6             VARCHAR(150),
    global_attribute7             VARCHAR(150),
    global_attribute8             VARCHAR(150),
    global_attribute9             VARCHAR(150),
    global_attribute10            VARCHAR(150),
    global_attribute11            VARCHAR(150),
    global_attribute12            VARCHAR(150),
    global_attribute13            VARCHAR(150),
    global_attribute14            VARCHAR(150),
    global_attribute15            VARCHAR(150),
    global_attribute16            VARCHAR(150),
    global_attribute17            VARCHAR(150),
    global_attribute18            VARCHAR(150),
    global_attribute19            VARCHAR(150),
    global_attribute20            VARCHAR(150),
    tp_header_id                  bigint,
    ece_tp_location_code          VARCHAR(60),
    pcard_site_flag               VARCHAR(1),
    match_option                  VARCHAR(25),
    country_of_origin_code        VARCHAR(2),
    future_dated_payment_ccid     bigint,
    create_debit_memo_flag        VARCHAR(25),
    supplier_notif_method         VARCHAR(25),
    email_address                 VARCHAR(2000),
    primary_pay_site_flag         VARCHAR(1),
    shipping_control              VARCHAR(30),
    selling_company_identifier    VARCHAR(10),
    gapless_inv_num_flag          VARCHAR(1),
    duns_number                   VARCHAR(30),
    location_id                   bigint,
    party_site_id                 bigint,
    tolerance_id                  bigint,
    services_tolerance_id         bigint,
    retainage_rate                bigint,
    edi_id_number                 VARCHAR(30),
    vat_registration_num          VARCHAR(20),
    language_code                 VARCHAR(4),
    payment_method_lookup_code    VARCHAR(25),
    bank_account_name             VARCHAR(80),
    bank_account_num              VARCHAR(30),
    bank_num                      VARCHAR(25),
    bank_account_type             VARCHAR(25),
    current_catalog_num           VARCHAR(20),
    vat_code                      VARCHAR(30),
    ap_tax_rounding_rule          VARCHAR(1),
    auto_tax_calc_flag            VARCHAR(1),
    auto_tax_calc_override        VARCHAR(1),
    amount_includes_tax_flag      VARCHAR(1),
    offset_vat_code               VARCHAR(20),
    bank_number                   VARCHAR(30),
    bank_branch_type              VARCHAR(25),
    offset_tax_flag               VARCHAR(1),
    remittance_email              VARCHAR(2000),
    edi_transaction_handling      VARCHAR(25),
    edi_payment_method            VARCHAR(25),
    edi_payment_format            VARCHAR(25),
    edi_remittance_method         VARCHAR(25),
    edi_remittance_instruction    VARCHAR(256),
    exclusive_payment_flag        VARCHAR(1),
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- 采购供应商表：po_vendors
create table PO_VENDORS_01
(
    vendor_id                      bigint not null,
    last_update_date               datetime not null,
    last_updated_by                bigint not null,
    vendor_name                    VARCHAR(240),
    vendor_name_alt                VARCHAR(320),
    segment1                       VARCHAR(30) not null,
    summary_flag                   VARCHAR(1) not null,
    enabled_flag                   VARCHAR(1) not null,
    segment2                       VARCHAR(30),
    segment3                       VARCHAR(30),
    segment4                       VARCHAR(30),
    segment5                       VARCHAR(30),
    last_update_login              bigint,
    creation_date                  datetime not null,
    created_by                     bigint not null,
    employee_id                    bigint,
    vendor_type_lookup_code        VARCHAR(30),
    customer_num                   VARCHAR(25),
    one_time_flag                  VARCHAR(1),
    parent_vendor_id               bigint,
    min_order_amount               bigint,
    terms_id                       bigint,
    set_of_books_id                bigint,
    always_take_disc_flag          VARCHAR(1),
    pay_date_basis_lookup_code     VARCHAR(25),
    pay_group_lookup_code          VARCHAR(25),
    payment_priority               bigint,
    invoice_currency_code          VARCHAR(15),
    payment_currency_code          VARCHAR(15),
    invoice_amount_limit           bigint,
    hold_all_payments_flag         VARCHAR(1),
    hold_future_payments_flag      VARCHAR(1),
    hold_reason                    VARCHAR(240),
    num_1099                       VARCHAR(20),
    individual_1099                VARCHAR(30),
    type_1099                      VARCHAR(10),
    withholding_status_lookup_code VARCHAR(25),
    withholding_start_date         datetime,
    organization_type_lookup_code  VARCHAR(25),
    start_date_active              datetime,
    end_date_active                datetime,
    minority_group_lookup_code     VARCHAR(25),
    women_owned_flag               VARCHAR(1),
    small_business_flag            VARCHAR(1),
    standard_industry_class        VARCHAR(25),
    hold_flag                      VARCHAR(1),
    purchasing_hold_reason         VARCHAR(240),
    hold_by                        bigint,
    hold_date                      datetime,
    terms_date_basis               VARCHAR(25),
    inspection_required_flag       VARCHAR(1),
    receipt_required_flag          VARCHAR(1),
    qty_rcv_tolerance              bigint,
    qty_rcv_exception_code         VARCHAR(25),
    enforce_ship_to_location_code  VARCHAR(25),
    days_early_receipt_allowed     bigint,
    days_late_receipt_allowed      bigint,
    receipt_days_exception_code    VARCHAR(25),
    receiving_routing_id           bigint,
    allow_substitute_receipts_flag VARCHAR(1),
    allow_unordered_receipts_flag  VARCHAR(1),
    hold_unmatched_invoices_flag   VARCHAR(1),
    tax_verification_date          datetime,
    name_control                   VARCHAR(4),
    state_reportable_flag          VARCHAR(1),
    federal_reportable_flag        VARCHAR(1),
    attribute_category             VARCHAR(30),
    attribute1                     VARCHAR(150),
    attribute2                     VARCHAR(150),
    attribute3                     VARCHAR(150),
    attribute4                     VARCHAR(150),
    attribute5                     VARCHAR(150),
    attribute6                     VARCHAR(150),
    attribute7                     VARCHAR(150),
    attribute8                     VARCHAR(150),
    attribute9                     VARCHAR(150),
    attribute10                    VARCHAR(150),
    attribute11                    VARCHAR(150),
    attribute12                    VARCHAR(150),
    attribute13                    VARCHAR(150),
    attribute14                    VARCHAR(150),
    attribute15                    VARCHAR(150),
    request_id                     bigint,
    program_application_id         bigint,
    program_id                     bigint,
    program_update_date            datetime,
    vat_registration_num           VARCHAR(40),
    auto_calculate_interest_flag   VARCHAR(1),
    validation_number              bigint,
    exclude_freight_from_discount  VARCHAR(1),
    tax_reporting_name             VARCHAR(80),
    check_digits                   VARCHAR(30),
    allow_awt_flag                 VARCHAR(1),
    awt_group_id                   bigint,
    global_attribute1              VARCHAR(150),
    global_attribute2              VARCHAR(150),
    global_attribute3              VARCHAR(150),
    global_attribute4              VARCHAR(150),
    global_attribute5              VARCHAR(150),
    global_attribute6              VARCHAR(150),
    global_attribute7              VARCHAR(150),
    global_attribute8              VARCHAR(150),
    global_attribute9              VARCHAR(150),
    global_attribute10             VARCHAR(150),
    global_attribute11             VARCHAR(150),
    global_attribute12             VARCHAR(150),
    global_attribute13             VARCHAR(150),
    global_attribute14             VARCHAR(150),
    global_attribute15             VARCHAR(150),
    global_attribute16             VARCHAR(150),
    global_attribute17             VARCHAR(150),
    global_attribute18             VARCHAR(150),
    global_attribute19             VARCHAR(150),
    global_attribute20             VARCHAR(150),
    global_attribute_category      VARCHAR(30),
    bank_charge_bearer             VARCHAR(1),
    match_option                   VARCHAR(25),
    create_debit_memo_flag         VARCHAR(25),
    party_id                       bigint,
    parent_party_id                bigint,
    ni_number                      VARCHAR(30),
    party_number                   VARCHAR(30) not null,
    pay_awt_group_id               bigint,
    ods_creation_date              datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


--
-- Create table
create table AP_XLA_AE_HEADERS_01
(
    ae_header_id                   bigint not null,
    application_id                 bigint not null,
    ledger_id                      bigint not null,
    entity_id                      bigint not null,
    event_id                       bigint not null,
    event_type_code                VARCHAR(30) not null,
    accounting_date                datetime not null,
    gl_transfer_status_code        VARCHAR(30) not null,
    gl_transfer_date               datetime,
    je_category_name               VARCHAR(30) not null,
    accounting_entry_status_code   VARCHAR(30) not null,
    accounting_entry_type_code     VARCHAR(30) not null,
    amb_context_code               VARCHAR(30),
    product_rule_type_code         VARCHAR(1),
    product_rule_code              VARCHAR(30),
    product_rule_version           VARCHAR(30),
    description                    VARCHAR(1996),
    doc_sequence_id                bigint,
    doc_sequence_value             bigint,
    accounting_batch_id            bigint,
    completion_acct_seq_version_id bigint,
    close_acct_seq_version_id      bigint,
    completion_acct_seq_value      bigint,
    close_acct_seq_value           bigint,
    budget_version_id              bigint,
    funds_status_code              VARCHAR(30),
    encumbrance_type_id            bigint,
    balance_type_code              VARCHAR(1) not null,
    reference_date                 datetime,
    completed_date                 datetime,
    period_name                    VARCHAR(15),
    packet_id                      bigint,
    completion_acct_seq_assign_id  bigint,
    close_acct_seq_assign_id       bigint,
    doc_category_code              VARCHAR(30),
    attribute_category             VARCHAR(30),
    attribute1                     VARCHAR(150),
    attribute2                     VARCHAR(150),
    attribute3                     VARCHAR(150),
    attribute4                     VARCHAR(150),
    attribute5                     VARCHAR(150),
    attribute6                     VARCHAR(150),
    attribute7                     VARCHAR(150),
    attribute8                     VARCHAR(150),
    attribute9                     VARCHAR(150),
    attribute10                    VARCHAR(150),
    attribute11                    VARCHAR(150),
    attribute12                    VARCHAR(150),
    attribute13                    VARCHAR(150),
    attribute14                    VARCHAR(150),
    attribute15                    VARCHAR(150),
    group_id                       bigint,
    doc_sequence_version_id        bigint,
    doc_sequence_assign_id         bigint,
    creation_date                  datetime not null,
    created_by                     bigint not null,
    last_update_date               datetime not null,
    last_updated_by                bigint not null,
    last_update_login              bigint,
    program_update_date            datetime,
    program_application_id         bigint,
    program_id                     bigint,
    request_id                     bigint,
    upg_batch_id                   bigint,
    upg_source_application_id      bigint,
    upg_valid_flag                 VARCHAR(1),
    zero_amount_flag               VARCHAR(1),
    parent_ae_header_id            bigint,
    parent_ae_line_num             bigint,
    accrual_reversal_flag          VARCHAR(1),
    merge_event_id                 bigint,
    need_bal_flag                  VARCHAR(1),
    ods_creation_date              datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


create table AP_XLA_AE_LINES_01
(
    ae_header_id              bigint not null,
    ae_line_num               bigint not null,
    application_id            bigint not null,
    code_combination_id       bigint not null,
    gl_transfer_mode_code     VARCHAR(1),
    gl_sl_link_id             bigint,
    accounting_class_code     VARCHAR(30) not null,
    party_id                  bigint,
    party_site_id             bigint,
    party_type_code           VARCHAR(1),
    entered_dr                bigint,
    entered_cr                bigint,
    accounted_dr              bigint,
    accounted_cr              bigint,
    description               VARCHAR(1996),
    statistical_amount        bigint,
    currency_code             VARCHAR(15) not null,
    currency_conversion_date  datetime,
    currency_conversion_rate  bigint,
    currency_conversion_type  VARCHAR(30),
    ussgl_transaction_code    VARCHAR(30),
    jgzz_recon_ref            VARCHAR(240),
    control_balance_flag      VARCHAR(1),
    analytical_balance_flag   VARCHAR(1),
    attribute_category        VARCHAR(30),
    attribute1                VARCHAR(150),
    attribute2                VARCHAR(150),
    attribute3                VARCHAR(150),
    attribute4                VARCHAR(150),
    attribute5                VARCHAR(150),
    attribute6                VARCHAR(150),
    attribute7                VARCHAR(150),
    attribute8                VARCHAR(150),
    attribute9                VARCHAR(150),
    attribute10               VARCHAR(150),
    attribute11               VARCHAR(150),
    attribute12               VARCHAR(150),
    attribute13               VARCHAR(150),
    attribute14               VARCHAR(150),
    attribute15               VARCHAR(150),
    gl_sl_link_table          VARCHAR(30),
    displayed_line_number     bigint,
    creation_date             datetime not null,
    created_by                bigint not null,
    last_update_date          datetime not null,
    last_updated_by           bigint not null,
    last_update_login         bigint,
    program_update_date       datetime,
    program_application_id    bigint,
    program_id                bigint,
    request_id                bigint,
    upg_batch_id              bigint,
    upg_tax_reference_id1     bigint,
    upg_tax_reference_id2     bigint,
    upg_tax_reference_id3     bigint,
    unrounded_accounted_dr    bigint,
    unrounded_accounted_cr    bigint,
    gain_or_loss_flag         VARCHAR(1),
    unrounded_entered_dr      bigint,
    unrounded_entered_cr      bigint,
    substituted_ccid          bigint,
    business_class_code       VARCHAR(30),
    mpa_accrual_entry_flag    VARCHAR(1),
    encumbrance_type_id       bigint,
    funds_status_code         VARCHAR(30),
    merge_code_combination_id bigint,
    merge_party_id            bigint,
    merge_party_site_id       bigint,
    accounting_date           datetime not null,
    ledger_id                 bigint not null,
    source_table              VARCHAR(30),
    source_id                 bigint,
    account_overlay_source_id bigint,
    ods_creation_date         datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


create table AP_XLA_DIS_LINKS_01
(
    application_id                bigint not null,
    event_id                      bigint not null,
    ae_header_id                  bigint not null,
    ae_line_num                   bigint not null,
    source_distribution_type      VARCHAR(30) not null,
    source_distribution_id_char_1 VARCHAR(240),
    source_distribution_id_char_2 VARCHAR(240),
    source_distribution_id_char_3 VARCHAR(240),
    source_distribution_id_char_4 VARCHAR(240),
    source_distribution_id_char_5 VARCHAR(240),
    source_distribution_id_num_1  bigint,
    source_distribution_id_num_2  bigint,
    source_distribution_id_num_3  bigint,
    source_distribution_id_num_4  bigint,
    source_distribution_id_num_5  bigint,
    tax_line_ref_id               bigint,
    tax_summary_line_ref_id       bigint,
    tax_rec_nrec_dist_ref_id      bigint,
    statistical_amount            bigint,
    ref_ae_header_id              bigint not null,
    ref_temp_line_num             bigint,
    accounting_line_code          VARCHAR(30),
    accounting_line_type_code     VARCHAR(1),
    merge_duplicate_code          VARCHAR(1) not null,
    temp_line_num                 bigint not null,
    ref_event_id                  bigint,
    line_definition_owner_code    VARCHAR(30),
    line_definition_code          VARCHAR(30),
    event_class_code              VARCHAR(30),
    event_type_code               VARCHAR(30),
    upg_batch_id                  bigint,
    calculate_acctd_amts_flag     VARCHAR(1),
    calculate_g_l_amts_flag       VARCHAR(1),
    rounding_class_code           VARCHAR(30),
    document_rounding_level       VARCHAR(30),
    unrounded_entered_dr          bigint,
    unrounded_entered_cr          bigint,
    doc_rounding_entered_amt      bigint,
    doc_rounding_acctd_amt        bigint,
    unrounded_accounted_cr        bigint,
    unrounded_accounted_dr        bigint,
    applied_to_application_id     bigint,
    applied_to_entity_code        VARCHAR(30),
    applied_to_entity_id          bigint,
    applied_to_source_id_num_1    bigint,
    applied_to_source_id_num_2    bigint,
    applied_to_source_id_num_3    bigint,
    applied_to_source_id_num_4    bigint,
    applied_to_source_id_char_1   VARCHAR(30),
    applied_to_source_id_char_2   VARCHAR(30),
    applied_to_source_id_char_3   VARCHAR(30),
    applied_to_source_id_char_4   VARCHAR(30),
    applied_to_distribution_type  VARCHAR(30),
    applied_to_dist_id_num_1      bigint,
    applied_to_dist_id_num_2      bigint,
    applied_to_dist_id_num_3      bigint,
    applied_to_dist_id_num_4      bigint,
    applied_to_dist_id_num_5      bigint,
    applied_to_dist_id_char_1     VARCHAR(30),
    applied_to_dist_id_char_2     VARCHAR(30),
    applied_to_dist_id_char_3     VARCHAR(30),
    applied_to_dist_id_char_4     VARCHAR(30),
    applied_to_dist_id_char_5     VARCHAR(30),
    alloc_to_application_id       bigint,
    alloc_to_entity_code          VARCHAR(30),
    alloc_to_source_id_num_1      bigint,
    alloc_to_source_id_num_2      bigint,
    alloc_to_source_id_num_3      bigint,
    alloc_to_source_id_num_4      bigint,
    alloc_to_source_id_char_1     VARCHAR(30),
    alloc_to_source_id_char_2     VARCHAR(30),
    alloc_to_source_id_char_3     VARCHAR(30),
    alloc_to_source_id_char_4     VARCHAR(30),
    alloc_to_distribution_type    VARCHAR(30),
    alloc_to_dist_id_num_1        bigint,
    alloc_to_dist_id_num_2        bigint,
    alloc_to_dist_id_num_3        bigint,
    alloc_to_dist_id_num_4        bigint,
    alloc_to_dist_id_num_5        bigint,
    alloc_to_dist_id_char_1       VARCHAR(30),
    alloc_to_dist_id_char_2       VARCHAR(30),
    alloc_to_dist_id_char_3       VARCHAR(30),
    alloc_to_dist_id_char_4       VARCHAR(30),
    alloc_to_dist_id_char_5       VARCHAR(30),
    gain_or_loss_ref              VARCHAR(30),
    ods_creation_date             datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- Create table
create table AP_XLA_TRX_ENTITIES_01
(
    entity_id                 bigint not null,
    application_id            bigint not null,
    legal_entity_id           bigint,
    entity_code               VARCHAR(30) not null,
    creation_date             datetime not null,
    created_by                bigint not null,
    last_update_date          datetime not null,
    last_updated_by           bigint not null,
    last_update_login         bigint,
    source_id_int_1           bigint,
    source_id_char_1          VARCHAR(30),
    security_id_int_1         bigint,
    security_id_int_2         bigint,
    security_id_int_3         bigint,
    security_id_char_1        VARCHAR(30),
    security_id_char_2        VARCHAR(30),
    security_id_char_3        VARCHAR(30),
    source_id_int_2           bigint,
    source_id_char_2          VARCHAR(30),
    source_id_int_3           bigint,
    source_id_char_3          VARCHAR(30),
    source_id_int_4           bigint,
    source_id_char_4          VARCHAR(30),
    transaction_number        VARCHAR(240),
    ledger_id                 bigint not null,
    valuation_method          VARCHAR(30),
    source_application_id     bigint not null,
    upg_batch_id              bigint,
    upg_source_application_id bigint,
    upg_valid_flag            VARCHAR(1),
    ods_creation_date         datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


-- Create table
create table FND_USER_01
(
    user_id                 bigint not null,  ---(OK)
    user_name               VARCHAR(100) not null,  ---(OK)
    last_update_date        datetime not null,
    last_updated_by         bigint not null,
    creation_date           datetime not null,
    created_by              bigint not null,
    last_update_login       bigint,
    session_number          bigint not null,
    start_date              datetime not null,
    end_date                datetime,
    description             VARCHAR(240),
    last_logon_date         datetime,
    employee_id             bigint,
    email_address           VARCHAR(240),
    fax                     VARCHAR(80),
    customer_id             bigint,
    supplier_id             bigint,
    web_password            VARCHAR(240),
    user_guid               BLOB(16),
    gcn_code_combination_id bigint,
    person_party_id         bigint,
    ods_creation_date       datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;


create table GL_LEDGERS_01
(
    ledger_id                      bigint not null,
    name                           VARCHAR(30) not null,
    short_name                     VARCHAR(20) not null,
    description                    VARCHAR(240),
    ledger_category_code           VARCHAR(30) not null,
    alc_ledger_type_code           VARCHAR(30) not null,
    object_type_code               VARCHAR(1) not null,
    le_ledger_type_code            VARCHAR(1) not null,
    completion_status_code         VARCHAR(30),
    configuration_id               bigint,
    chart_of_accounts_id           bigint not null,
    currency_code                  VARCHAR(15) not null,
    period_set_name                VARCHAR(15) not null,
    accounted_period_type          VARCHAR(15) not null,
    first_ledger_period_name       VARCHAR(15) not null,
    ret_earn_code_combination_id   bigint not null,
    suspense_allowed_flag          VARCHAR(1) not null,
    allow_intercompany_post_flag   VARCHAR(1) not null,
    track_rounding_imbalance_flag  VARCHAR(1) not null,
    enable_average_balances_flag   VARCHAR(1) not null,
    cum_trans_code_combination_id  bigint,
    res_encumb_code_combination_id bigint,
    net_income_code_combination_id bigint,
    rounding_code_combination_id   bigint,
    enable_budgetary_control_flag  VARCHAR(1) not null,
    require_budget_journals_flag   VARCHAR(1) not null,
    enable_je_approval_flag        VARCHAR(1) not null,
    enable_automatic_tax_flag      VARCHAR(1) not null,
    consolidation_ledger_flag      VARCHAR(1) not null,
    translate_eod_flag             VARCHAR(1) not null,
    translate_qatd_flag            VARCHAR(1) not null,
    translate_yatd_flag            VARCHAR(1) not null,
    transaction_calendar_id        bigint,
    daily_translation_rate_type    VARCHAR(30),
    automatically_created_flag     VARCHAR(1) not null,
    bal_seg_value_option_code      VARCHAR(1) not null,
    bal_seg_column_name            VARCHAR(25) not null,
    mgt_seg_value_option_code      VARCHAR(1) not null,
    mgt_seg_column_name            VARCHAR(25),
    bal_seg_value_set_id           bigint not null,
    mgt_seg_value_set_id           bigint,
    implicit_access_set_id         bigint,
    criteria_set_id                bigint,
    future_enterable_periods_limit bigint not null,
    ledger_attributes              VARCHAR(2000) not null,
    implicit_ledger_set_id         bigint,
    latest_opened_period_name      VARCHAR(15),
    latest_encumbrance_year        bigint,
    period_average_rate_type       VARCHAR(30),
    period_end_rate_type           VARCHAR(30),
    budget_period_avg_rate_type    VARCHAR(30),
    budget_period_end_rate_type    VARCHAR(30),
    sla_accounting_method_code     VARCHAR(30),
    sla_accounting_method_type     VARCHAR(1),
    sla_description_language       VARCHAR(15),
    sla_entered_cur_bal_sus_ccid   bigint,
    sla_sequencing_flag            VARCHAR(1),
    sla_bal_by_ledger_curr_flag    VARCHAR(1),
    sla_ledger_cur_bal_sus_ccid    bigint,
    enable_secondary_track_flag    VARCHAR(1),
    enable_reval_ss_track_flag     VARCHAR(1),
    last_update_date               datetime not null,
    last_updated_by                bigint not null,
    creation_date                  datetime not null,
    created_by                     bigint not null,
    last_update_login              bigint,
    context                        VARCHAR(150),
    attribute1                     VARCHAR(150),
    attribute2                     VARCHAR(150),
    attribute3                     VARCHAR(150),
    attribute4                     VARCHAR(150),
    attribute5                     VARCHAR(150),
    attribute6                     VARCHAR(150),
    attribute7                     VARCHAR(150),
    attribute8                     VARCHAR(150),
    attribute9                     VARCHAR(150),
    attribute10                    VARCHAR(150),
    attribute11                    VARCHAR(150),
    attribute12                    VARCHAR(150),
    attribute13                    VARCHAR(150),
    attribute14                    VARCHAR(150),
    attribute15                    VARCHAR(150),
    enable_reconciliation_flag     VARCHAR(1) not null,
    create_je_flag                 VARCHAR(1) not null,
    sla_ledger_cash_basis_flag     VARCHAR(1),
    complete_flag                  VARCHAR(1),
    commitment_budget_flag         VARCHAR(1),
    net_closing_bal_flag           CHAR(1),
    automate_sec_jrnl_rev_flag     CHAR(1),
    ods_creation_date              datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- UROWID
create table AP_GL_IMPORT_REFERENCES_01
(
    row_id                       VARCHAR(4000) not null,-- UROWID
    je_batch_id                  bigint not null,
    je_header_id                 bigint not null,
    je_line_num                  bigint not null,
    last_update_date             datetime not null,
    last_updated_by              bigint not null,
    creation_date                datetime,
    created_by                   bigint,
    last_update_login            bigint,
    reference_1                  VARCHAR(240),
    reference_2                  VARCHAR(240),
    reference_3                  VARCHAR(240),
    reference_4                  VARCHAR(240),
    reference_5                  VARCHAR(240),
    reference_6                  VARCHAR(240),
    reference_7                  VARCHAR(240),
    reference_8                  VARCHAR(240),
    reference_9                  VARCHAR(240),
    reference_10                 VARCHAR(240),
    subledger_doc_sequence_id    bigint,
    subledger_doc_sequence_value bigint,
    gl_sl_link_id                bigint,
    gl_sl_link_table             VARCHAR(30),
    ods_creation_date            datetime
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;

-- Create table
create table QGL_APPROVE_01
(
    je_header_id    bigint,  --(OK)
    post_person     bigint,  --(OK)
    post_date       datetime,  --(OK)
    ods_create_date datetime  --(OK)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;